/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AnimeRouteRouteImport } from './routes/anime/route'
import { Route as AnimeIndexRouteImport } from './routes/anime/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AnimeFeaturedAnimeRouteImport } from './routes/anime/featured-anime'
import { Route as AnimeBookmarkRouteImport } from './routes/anime/bookmark'
import { Route as AnimeWatchIdRouteImport } from './routes/anime/watch/$id'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeRouteRoute = AnimeRouteRouteImport.update({
  id: '/anime',
  path: '/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnimeRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AnimeFeaturedAnimeRoute = AnimeFeaturedAnimeRouteImport.update({
  id: '/featured-anime',
  path: '/featured-anime',
  getParentRoute: () => AnimeRouteRoute,
} as any)
const AnimeBookmarkRoute = AnimeBookmarkRouteImport.update({
  id: '/bookmark',
  path: '/bookmark',
  getParentRoute: () => AnimeRouteRoute,
} as any)
const AnimeWatchIdRoute = AnimeWatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => AnimeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/anime': typeof AnimeRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/anime/bookmark': typeof AnimeBookmarkRoute
  '/anime/featured-anime': typeof AnimeFeaturedAnimeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/anime/': typeof AnimeIndexRoute
  '/anime/watch/$id': typeof AnimeWatchIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/anime/bookmark': typeof AnimeBookmarkRoute
  '/anime/featured-anime': typeof AnimeFeaturedAnimeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/anime': typeof AnimeIndexRoute
  '/anime/watch/$id': typeof AnimeWatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/anime': typeof AnimeRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/anime/bookmark': typeof AnimeBookmarkRoute
  '/anime/featured-anime': typeof AnimeFeaturedAnimeRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/anime/': typeof AnimeIndexRoute
  '/anime/watch/$id': typeof AnimeWatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/anime'
    | '/auth'
    | '/anime/bookmark'
    | '/anime/featured-anime'
    | '/auth/login'
    | '/auth/register'
    | '/anime/'
    | '/anime/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/anime/bookmark'
    | '/anime/featured-anime'
    | '/auth/login'
    | '/auth/register'
    | '/anime'
    | '/anime/watch/$id'
  id:
    | '__root__'
    | '/anime'
    | '/auth'
    | '/anime/bookmark'
    | '/anime/featured-anime'
    | '/auth/login'
    | '/auth/register'
    | '/anime/'
    | '/anime/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AnimeRouteRoute: typeof AnimeRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime': {
      id: '/anime'
      path: '/anime'
      fullPath: '/anime'
      preLoaderRoute: typeof AnimeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof AnimeRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/anime/featured-anime': {
      id: '/anime/featured-anime'
      path: '/featured-anime'
      fullPath: '/anime/featured-anime'
      preLoaderRoute: typeof AnimeFeaturedAnimeRouteImport
      parentRoute: typeof AnimeRouteRoute
    }
    '/anime/bookmark': {
      id: '/anime/bookmark'
      path: '/bookmark'
      fullPath: '/anime/bookmark'
      preLoaderRoute: typeof AnimeBookmarkRouteImport
      parentRoute: typeof AnimeRouteRoute
    }
    '/anime/watch/$id': {
      id: '/anime/watch/$id'
      path: '/watch/$id'
      fullPath: '/anime/watch/$id'
      preLoaderRoute: typeof AnimeWatchIdRouteImport
      parentRoute: typeof AnimeRouteRoute
    }
  }
}

interface AnimeRouteRouteChildren {
  AnimeBookmarkRoute: typeof AnimeBookmarkRoute
  AnimeFeaturedAnimeRoute: typeof AnimeFeaturedAnimeRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  AnimeWatchIdRoute: typeof AnimeWatchIdRoute
}

const AnimeRouteRouteChildren: AnimeRouteRouteChildren = {
  AnimeBookmarkRoute: AnimeBookmarkRoute,
  AnimeFeaturedAnimeRoute: AnimeFeaturedAnimeRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  AnimeWatchIdRoute: AnimeWatchIdRoute,
}

const AnimeRouteRouteWithChildren = AnimeRouteRoute._addFileChildren(
  AnimeRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AnimeRouteRoute: AnimeRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
